# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - plan-api2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: plan-admin
          path: '${{ github.workspace }}/plan-admin/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'plan-admin'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: plan-admin

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'plan-admin'
          slot-name: 'plan-admin'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0F8A7D505A0E482495C99256F9E6F92E }}
          package: '*.jar'
