# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - scflowcasting(api)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://crpi-neusdnicxn2uvfgv.ap-southeast-1.personal.cr.aliyuncs.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_ca30dc2ae62647fbbc2ccb5899f473b4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_15e3f8d7ac544ef28e889f8f6a820df0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: crpi-neusdnicxn2uvfgv.ap-southeast-1.personal.cr.aliyuncs.com/${{ secrets.AzureAppService_ContainerUsername_ca30dc2ae62647fbbc2ccb5899f473b4 }}/kokl-plan/plan:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'api'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'scflowcasting'
        slot-name: 'api'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_aca8a2e6e95b4caa960e92e0b52b249d }}
        images: 'crpi-neusdnicxn2uvfgv.ap-southeast-1.personal.cr.aliyuncs.com/${{ secrets.AzureAppService_ContainerUsername_ca30dc2ae62647fbbc2ccb5899f473b4 }}/kokl-plan/plan:${{ github.sha }}'